language: objective-c
osx_image: xcode7.3

before_install:
   - sudo gem install cocoapods
   - pod repo update

script: xcodebuild -workspace CHProgressSuit.xcworkspace -scheme CHProgressSuit -sdk iphonesimulator